name: SimpeCICD
on: 
 push:   
  branches:
   -master
jobs:
   GetVersions:
    runs-on: ubuntu-latest
    steps:
       - name: netversion
         run: dotnet --version
       
   
  
      

    
  
